# 7.1

In [5]:
import pandas as pd 

df = pd.read_json('/media/trong-thanh/Data/University/Fourth Year/NLP/experiments/ex1/data.json', lines = True)
df.head()

,text,timestamp,url
0,Beginners BBQ Class Taking Place in Missoula!\...,2019-04-25 12:57:54+00:00,https://klyq.com/beginners-bbq-class-taking-pl...
1,Discussion in 'Mac OS X Lion (10.7)' started b...,2019-04-21 10:07:13+00:00,https://forums.macrumors.com/threads/restore-f...
2,Foil plaid lycra and spandex shortall with met...,2019-04-25 10:40:23+00:00,https://awishcometrue.com/Catalogs/Clearance/T...
3,How many backlinks per day for new site?\nDisc...,2019-04-21 12:46:19+00:00,https://www.blackhatworld.com/seo/how-many-bac...
4,The Denver Board of Education opened the 2017-...,2019-04-20 14:33:21+00:00,http://bond.dpsk12.org/category/news/

# 7.2

In [7]:
df['clean_text'] = (
    df['text']
    .fillna("")
    .str.lower()
    .str.replace(r'[^a-z0-9\s]', ' ', regex=True)
    .str.replace(r'\s+', ' ', regex=True)
    .str.strip()
)
df.head()

,text,timestamp,url,clean_text
0,Beginners BBQ Class Taking Place in Missoula!\...,2019-04-25 12:57:54+00:00,https://klyq.com/beginners-bbq-class-taking-pl...,beginners bbq class taking place in missoula d...
1,Discussion in 'Mac OS X Lion (10.7)' started b...,2019-04-21 10:07:13+00:00,https://forums.macrumors.com/threads/restore-f...,discussion in mac os x lion 10 7 started by ax...
2,Foil plaid lycra and spandex shortall with met...,2019-04-25 10:40:23+00:00,https://awishcometrue.com/Catalogs/Clearance/T...,foil plaid lycra and spandex shortall with met...
3,How many backlinks per day for new site?\nDisc...,2019-04-21 12:46:19+00:00,https://www.blackhatworld.com/seo/how-many-bac...,how many backlinks per day for new site discus...
4,The Denver Board of Education opened the 2017-...,2019-04-20 14:33:21+00:00,http://bond.dpsk12.org/category/news/,the denver board of education opened the 2017 ...

# 7.3

In [14]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
X_counter = vectorizer.fit_transform(df['clean_text'])
print(f'Shape: {X_counter.shape}')
print(X_counter)

Shape: (30000, 186582)
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 4981696 stored elements and shape (30000, 186582)>
  Coords	Values
  (0, 25537)	1
  (0, 24928)	4
  (0, 39862)	4
  (0, 163491)	1
  (0, 130163)	1
  (0, 85196)	4
  (0, 110928)	1
  (0, 53714)	1
  (0, 185031)	5
  (0, 179407)	1
  (0, 168005)	5
  (0, 71973)	2
  (0, 26745)	2
  (0, 20945)	1
  (0, 104328)	1
  (0, 49782)	1
  (0, 181736)	5
  (0, 78127)	1
  (0, 166044)	4
  (0, 122420)	1
  (0, 135978)	1
  (0, 166665)	1
  (0, 121809)	1
  (0, 185083)	1
  (0, 33821)	1
  :	:
  (29999, 147475)	1
  (29999, 83782)	1
  (29999, 98770)	1
  (29999, 170702)	2
  (29999, 141337)	1
  (29999, 126750)	1
  (29999, 120446)	2
  (29999, 182339)	4
  (29999, 182341)	1
  (29999, 62303)	2
  (29999, 63822)	2
  (29999, 185062)	1
  (29999, 46009)	3
  (29999, 98342)	3
  (29999, 21344)	1
  (29999, 154670)	1
  (29999, 51076)	1
  (29999, 127744)	2
  (29999, 87041)	1
  (29999, 46591)	1
  (29999, 62295)	1
  (29999, 180317)	1
  (29999, 88579)	1
  (29999, 136771)	2
  (29999, 141089)	1

Khi này:

N = 30000

V = 186582

# 7.4

In [10]:
N, V = X_counter.shape
print(f'N = {N}, V = {V}')

N = 30000, V = 186582

In [12]:
nnz = X_counter.nnz
total_elements = N * V
S = 1 - (nnz / total_elements)

print(f"Số lượng văn bản (N): {N:,}")
print(f"Kích thước từ điển (V): {V:,}")
print(f"Tổng số phần tử trong ma trận (N * V): {total_elements:,}")
print(f"Số phần tử khác 0 (nnz): {nnz:,}")
print(f"Tỷ lệ phần tử khác 0: {(nnz / total_elements) * 100:.4f}%")
print(f"Độ thưa Sparsity (S): {S:.6f} (tương đương {S * 100:.4f}%)")

Số lượng văn bản (N): 30,000
Kích thước từ điển (V): 186,582
Tổng số phần tử trong ma trận (N * V): 5,597,460,000
Số phần tử khác 0 (nnz): 4,981,696
Tỷ lệ phần tử khác 0: 0.0890%
Độ thưa Sparsity (S): 0.999110 (tương đương 99.9110%)

# 7.5

In [13]:
import numpy as np

feature_names = np.array(vectorizer.get_feature_names_out())
df_counts = np.array((X_counter > 0).sum(axis = 0)).flatten()

top_20 = np.argsort(df_counts)[::-1][:20]
print('Top 20 terns')
for rank, index in enumerate(top_20, 1):
    print(f'{rank:2d}. {feature_names[index]:<12}')

Top 20 terns
 1. the
 2. and
 3. to
 4. of
 5. in
 6. for
 7. is
 8. with
 9. on
10. that
11. this
12. are
13. it
14. as
15. at
16. from
17. be
18. you
19. by
20. have

In [15]:
from sklearn.feature_extraction.text import TfidfTransformer

tfidf_transformer = TfidfTransformer()
X_tfidf = tfidf_transformer.fit_transform(X_counter)
idfs = tfidf_transformer.idf_

In [16]:
top_20_idf = np.argsort(idfs)[::-1][:20]
print('Top 20 IDF')
for rank, index in enumerate(top_20_idf, 1):
    print(f'{rank:2d}. {feature_names[index]:<12}')

Top 20 IDF
 1. 00000
 2. zzzzzzz333
 3. zzzzzz
 4. 00003
 5. 000040
 6. 00005
 7. 0000856166
 8. 0001042
 9. 000116
10. 00012
11. 00015
12. 00016
13. 000165101
14. 0002
15. 00022
16. 000226
17. 000281
18. zwyn
19. zx636
20. zx6rr

In [17]:
tfidf_0 = X_tfidf.getrow(0).toarray().flatten()
top_20_tfidf_0 = np.argsort(tfidf_0)[::-1][:20]

for rank, index in enumerate(top_20_tfidf_0, 1):
    if tfidf_0[index] > 0:
        print(f'{rank:2d}. {feature_names[index]:<12}')

 1. bbq
 2. class
 3. meat
 4. balay
 5. kcbs
 6. lonestar
 7. will
 8. missoula
 9. apron
10. smoker
11. you
12. timelines
13. trimming
14. spectators
15. cost
16. rangers
17. 22nd
18. beginner
19. beginners
20. culinary

Trả lời:

- Từ xuất hienj nhiều trong toàn bộ corpus, khi đó DF = N, khi đó tỉ lệ N / DF = 1 => log (N / DF) = 0, khi đó xuất hiện nhiều lần trong văn bản, trọng số vẫn kéo gần về bằng 0.

- Một từ IDF cao => nó hiếm trong corpus. Đối với từ hiện đại trong văn bản, số lần xuất hiện bằng 0 => TF = 0 khi đó TF IDF = 0, từ đó IDF cao chỉ có giá trị cao trong chính tài liệu hiếm chứa nó.